{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ant-livechat.fullname" . }}
  labels:
    {{- include "ant-livechat.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}
{{- end }}