apiVersion: v2
name: ant-livechat
description: Hệ thống Livechat BeeIQ triển khai trên nền tảng Kubernetes
type: application

# Đây là phiên bản của gói Helm Chart
version: 1.0.1

# Đây là phiên bản của ứng dụng
appVersion: "1.0.1"

maintainers:
  - name: Thông Nguyễn
    email: thong.nguyen@antbuddy.com
    url: https://antbuddy.com

# Bạn có thể thay bằng link icon của BeeIQ nếu có
icon: https://antbuddy.com/assets/logo.png
